name: Package dev executables

on: [workflow_dispatch]
# https://data-dive.com/multi-os-deployment-in-cloud-using-pyinstaller-and-github-actions
jobs:
  build-win-dev:
    runs-on: windows-2019
    
    steps:
    
    - uses: actions/checkout@v2
      with:
        ref: dev

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install opencv-python numpy matplotlib scipy python-dateutil PySide2
        pip install hachoir orangebox vidgear qdarkstyle ffprobe-python darkdetect telemetry_parser

    - name: Package application
      run: |
        pyinstaller --icon=media\icon.ico -F gyroflow.py
        ren dist\gyroflow.exe gyroflow-dev.exe

    - uses: actions/upload-artifact@v2
      with:
        name: gyroflow_dev_exe
        path: dist/gyroflow-dev.exe
